FROM maven:3-jdk-11-slim@sha256:2cb7c73ba2fd0f7ae64cfabd99180030ec85841a1197b4ae821d21836cb0aa3b as buildtime

WORKDIR /build
COPY . .

RUN mvn clean package

FROM amazoncorretto:11@sha256:ad62c0f683aed0af8a92f1a0b5847b21675d26aeff15f9177857fbcc8cfb27f8 as runtime

WORKDIR /app

COPY --from=buildtime /build/target/*.jar /app/library.jar