# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Package

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types: [ closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      semver:
        required: true
        type: choice
        description: Select the new Semantic Version
        options:
          - major
          - minor
          - patch
          - buildNumber

# permissions given to the current action
permissions:
  packages: write
  contents: write

jobs:

  setup:
    name: Semver Setup
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.semver }}
    steps:
      - name: Set semver
        id: semver
        uses: pagopa/github-actions-template/semver-setup@483a0ceb9ef07dee34f7ce0de5b689cc3043eac4

  package:
    name: Publish Maven Package
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Make Release
        id: release
        uses: pagopa/github-actions-template/maven-release@483a0ceb9ef07dee34f7ce0de5b689cc3043eac4
        with:
          semver: ${{ needs.setup.outputs.semver }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Package
        id: package
        uses: pagopa/github-actions-template/maven-package@483a0ceb9ef07dee34f7ce0de5b689cc3043eac4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
